### ISSUE TITLE
move in cost - move in cost should scale with acres 

### ISSUE THREAD

**Issue by carlinstarrs** [USFS-PNW/Fia_Biosum_Scripts#16]
https://github.com/USFS-PNW/Fia_Biosum_Scripts/blob/b06df0618945a1357088f209a8a9a7221b2f8581/OPCOST/Opcost_10_0.R#L164

**Comment by carlinstarrs** [comment]
Currently, move in cost is calculated by taking the cost per hour of each machine in the system and multiplying it by 0.6533 (presumed to be a time conversion). The original function from 9_1.R is as follows: 

(Machine.Cost.Per.Hour*.35)*((30/25)+(30/45))

Yielding a value with units as cost, not cost/acre.

Other cost values are evaluated on a per acre bases. For example, total harvest cost is the sum of machine hours per acre times machine cost per hour for all machines in the harvest system. The final units are cost/acre. 

(Machine.Hours.Per.Acre) * (Machine.Cost.Per.Hour) 

Previous versions of opcost summed these values along with Move.In.Cost.LB to get total harvest_cpa  (according to the function named m5).

**Comment by jsfried** [comment]
To focus the question sightly:

Move-in costs were added in more recent versions of OpCost. They appear to have two components:
1. transportation of machines by lowboy to the operations site
2. set-up of equipment on the site to make it ready for productive operation

As coded in OpCost 9_1, component 1 is calculated for each machine as hours of transportation required (which is provided from BioSum) * lowboy cost per hour then divided by harvest area (in acres) and summed for all machines to get a move-in component #1 cost per acre.

Component #2 is calculated as Carlin documents above (machine specific hourly cost multiplied by a set of scalars that equate to 0.6533. It is NOT divided by harvest area but rather is applied to every acre, amounting to hundreds of dollars per acre in move-in costs being added to harvest_cpa. While move-in cost is reported in the OpCost output table, it is unfortunately only component #1 of the move in cost (the tiny amount) and it does not include the component #2 (huge amount, due to not dividing by harvest area), so this issue was not easily detected.

Question: Are we correct in understanding that this is a glitch and that component #2 should be divided by harvest area? And that move-in cost should be the sum of components #1 and #2 (when reported in the output table). We are 95% certain on this, but want to double-check with Rob or Conor.

**Comment by RobKeefe** [comment]
Conor would be the best one to verify that it was a mistake. It's not immediately clear to me why there's a need for two components to be calculated separately. Based on the description above, it does seem like you should be dividing by the number of acres to get a per-acre estimate. This sounds like it may be a likely cause of at least some of that large jump in total treatment cost that occurred systematically in these more recent versions of the model. Although not discussed here, I noticed that in plots comparing changes in the predictions that resulted in several subsequent versions of OpCost, using data Jeremy created. We discussed the change in predicted total treatment cost (typically around $1000 or more per stand, if I remember correctly) by email and on the phone a few weeks ago.

**Comment by jsfried** [comment]
We did not establish a need to calculate them separately, The request was for a total move-in cost on a per acre basis (with BioSum supplying hours of travel for equipment and area of the operation in acres). Going forward, let's treat this as an error and recode accordingly (divide total move in costs-- transportation and equipment setup, by acres to obtain a move in cost per acre). This is likely one element of the OpCost estimate increase, but accounts for only a quarter of it. Chipping issues, miscoded equations and other glitches found may also be a factor in the overestimation, and we are working to resolve these. Thanks for the help.

**Comment by RobKeefe** [comment]
Conor was working most closely with you (Jeremy) and the BioSum team on those move-in cost changes at your request, so you likely know best how it was supposed to look and whether Conor misinterpreted what you requested at that time. The 'chipping issues' seem to have been recurring for so long (measured in years...) that I wonder if it's worth having a broader discussion about 1) what is BioSum looking for; and 2) how best could that be represented in a useful model

**Comment by jsfried** [comment]
I would look forward to that conversation. I don't know whether  the issues are as much with the equations (though there are surely some) as with some serious coding errors.
