### ISSUE TITLE
calculate_hpa - check that NA values still mod brushcut values in

### ISSUE THREAD

**Issue by carlinstarrs** [USFS-PNW/Fia_Biosum_Scripts#18]
https://github.com/USFS-PNW/Fia_Biosum_Scripts/blob/b06df0618945a1357088f209a8a9a7221b2f8581/OPCOST/Opcost_10_0.R#L166

**Comment by carlinstarrs** [comment]
This functionality has been added. If any treated stand has a value that is Inf, NaN, or NA, it is evaluated as the equivalent of 0 when modifications are incorporated, meaning any modifiers that are summed to the hours per acre value will be added still.

**Comment by carlinstarrs** [comment]
@jsfried I implemented this but I want to make sure we are on the same page about what this means. 

Currently, three machines have a brush cut component (added in according to opcost_modifiers_ref): 

Harvester, Manual/Saw, and Feller Buncher. 

With this implemented, stands where the machine hours per acre would otherwise be NA/Inf/NaN will have a machine hours per acre equivalent to just the brush cut value. 

For any other machine, if the machine hours per acre is NA/Inf/NaN, it will remain that way since there are no modifiers added in. 

I just want to make sure we're okay with that.

**Comment by jsfried** [comment]
Wrt: "With this implemented, stands where the machine hours per acre would otherwise be NA/Inf/NaN will have a machine hours per acre equivalent to just the brush cut value."
Yes, they will have only brush cut values for that machine. Is it fair to assume that no other machines used in a system in which one of these machines are used will have non zero values in such cases?

WRT "For any other machine, if the machine hours per acre is NA/Inf/NaN, it will remain that way since there are no modifiers added in."
Will anything remain NaN or Inf (e.g., to diagnose issues) or do they get converted to NA? If the former, then all three will need to be trapped for in later stages so that errors do not get into OpCost Output, right? Or those cases get diverted to OpCost error tables (which BioSum could access and notify users that possible errors occurred)?

**Comment by carlinstarrs** [comment]
> Right now these just get carried through as NA values (so all the cost estimate values are also NA). They can be pulled anywhere as needed, I'll check with lesley toward the end in how biosum wants those tables.

And for reference, this happens to only about 7 stands in the entire dataset.

**Comment by carlinstarrs** [comment]
@jsfried  not sure if my responses above will go to your inbox or not so tagging you just in case

**Comment by jsfried** [comment]
It is hard to think of a case where a brush cutting "machine" would have zero for all but brush cutting and other machines would have non-zeros, but once OC10 is generating detailed tables for exploration, we can look for some!

Congrats on closing so many cases. I have unwatched the thread but will see updates on any thread I am participating in or have been @mentioned on, I think.
