### ISSUE TITLE
Implement limit parameters for opcost_ref calculations

### ISSUE THREAD

**Issue by carlinstarrs** [USFS-PNW/Fia_Biosum_Scripts#26]

**Comment by RobKeefe** [comment]
Not sure if this is referring to a mix-up you both had, or a goof of Conor's missing the large trees. I assume the latter. Just a note for the sake of posterity: I would caution against being too confident about predictions of tethered logging costs over the region that BioSum represents, since this logging system is still very experimental and changing quickly in different ways around the region. Because different equipment types are being used in different areas, e.g. a skidder rather than a shovel lowered down the hill, etc., the costs are likely to vary quite a lot in reality.

**Comment by jsfried** [comment]
No in this case, the goof-up was entirely mine :-) in that I had (intentionally) done my testing and comparisons with a dataset of Joshua's in which the prescriptions generated no large trees. But for the analysis we are doing now, we do have large trees to contend with and their felling cost needs to be accounted for. 

We appreciate that you are not confident in tethered systems estimates widely applied. We see them as potentially one end of a continuum (e.g., best case costs), so not entirely inappropriate for some analyses which are aspirational (what could be accomplished if there were motivation and commitment to do forest restoration at scale), much as the entire BioSum system is aspirational (if all non-reserved acres were really available for management, what could be done?). We know that not all acres are available so predictions ultimately can be scaled down by the pessimists, but one has to start somewhere. When we have a full working OpCost 10 with all systems operational, we can do some sensitivity analysis on how costs vary by system and the impacts those assumptions have on restoration feasibility at landscape scale. With this tethered system interim version, we are just trying to get one system up and running that we can use to generate plausible numbers for an analysis that is needed this week. The numbers that were coming out of OpCost have not been plausible due to a number of glitches, some now found and others not yet.
