### ISSUE TITLE
Deployment of Bolding equation

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia_Biosum_Scripts#28]
OpCost's implementation of the Bolding equation (that calculates chipping time in minutes) was:
Chippnig Time in Minutes = 0.001*(totalVol*25). I do not see this equation spelled out in the article, so it appears that some interpretation was made to arrive at this formulation- interpretation that I am not qualified to evaluate. In the emergency interim OpCost version we are striving to get working immediately we are using this equation for chippping chip sized trees (boles) and non commercial logs from the SL and LL size classes.

Is this equation correct and how do we get to it from the article?
[REF_150_BoldingLanford2005.pdf](https://github.com/USFS-PNW/Fia_Biosum_Scripts/files/1903824/REF_150_BoldingLanford2005.pdf)

**Comment by RobKeefe** [comment]
Hi All, this should really be 'assigned' to Conor, since he did the work with Jeremy and is by far the most knowledgeable. Providing the additional documentation and support is something Jeremy and Conor had an agreement on that I was not part of. I'll try to find a few minutes this evening to glance at some of Dr. Bolding's fuel treatment papers in order to try to understand what Conor coded in this case, and whether it appears to be correct. Chad Bolding has several papers on chipping stemming from his graduate work, so it's also possible this is not the correct reference.

**Comment by jsfried** [comment]
I think we need to face the fact that Conor is not available and will not likely become available. It is probably not productive to keep referring us back to Conor, as at this point, I have no evidence to support the hope that this would be a viable option. What I am hearing from you now is that Conor worked almost completely independently in designing OpCost, crafting its logic and selecting systems and equations. We did execute a supplemental agreement with Conor a year ago to complete documentation that I would have expected to have been part of the delivered final version of OpCost. Ultimately, Conor was apparently either unable or unwilling to perform that work, and the contract has lapsed, after being extended twice despite great reluctance on the part of our contracts officer (and only because I vouched for the idea that Conor would complete the work if given the additional chances). The contract officer is now firmly unwilling to grant any additional extensions. The unspent funds I begged from my team leader to support Conor will now go back to the Treasury, not to the Forest Service, and we have no more funds available in my Program for any purpose- we are a half million in the hole for this fiscal year, and budgets are shrinking.

We appreciate what time you can put in to the Bolding equation this evening, and your assistance in helping us understand what you know about OpCost and the equations within it.

**Comment by RobKeefe** [comment]
Hi Jeremy, before too many more threads get added here on GitHub, I want to
clarify why I do keep referring back: I'm really unable to discuss details
of the period prior to your agreement in a public forum like this. I can
explain why separately in an off-GitHub email or phone call, but there are
some important reasons. So, it puts me in a difficult spot trying to
provide answers to your questions in this framework. On the one hand, I
can't easily discuss the work prior to that agreement as framed in several
of these posts. I can discuss the work after that agreement, but of course
wasn't involved... So, it's a bit more tricky than may seem. I think it
best to discuss by phone or in a private communication by email, and how I
can best help.  As I've said elsewhere, it is unfortunate that things
didn't work out in that agreement, but since I wasn't involved, it's really
not my place to comment.

No, I would not characterize the past work in the same way you describe.
Happy to provide a better explanation by phone or email- Let's touch base!
Thanks,

Rob

**Comment by RobKeefe** [comment]
It's late when I was able to get to this, so please check that it makes sense. 

The equation in the Bolding reference predicts the time required to chip one forwarder load of logs. 
The input variable WT is the weight in pounds. So, whatever the current architecture, you should first convert the volume of the turn from cubic feet (or whatever units at the time...) to pounds if and when using this equation. Then, simply use something like: 

chiptimeperturnMin =  0.0015 * WT 

Where chiptimeperturnMin is in minutes and WT is in pounds per turn. E.g., for a 5000 pound forwarder 
turn weight, 0.0015*5000 = 7.5.  7.5 minutes is the total turn time required to chip that load of wood 
delivered by the forwarder. I don't see the addition of 25 in this paper and don't have the source for wherever it came from in the prior model, so lacking documentation I would say to leave that out. It may have been from another paper, or based on an assumption in a similar equation elsewhere.    

So, as a simple example, you could do, e.g., something like the following: 

## RK. Assume the weight per turn (WT) is 5000 pounds; WT = 5000 

WT <- 5000

## RK. Estimate the turn time based on Bolding and Landford (2005). FPJ 55:12. pp. 181-189.
## Per the reference, it includes wait time, feed time, and jam-clearing. It is a simple 
## linear function of turn weight in pounds (WT), chipping unmerchantable wood:

chiptimeperturnMin <- 0.0015*WT

## RK. Determine how many 'turns' (loads brought by the forwarder or skidder; not a truckload...) 
## are chipped per PMH: 

chiploadsperPMH <- 60/chiptimeperturnMin 

## RK. If desired, determine the production rate on a per-PMH basis, in pounds:

chiptonsperPMH <- (chiploadsperPMH*WT)/2000

## RK. Result (not run):

## chiptonsperPMH

##>20 

## RK. Check that this corresponds to results in Chad's paper. In his sampling, the mean weight per 
## forwarder load (turn) was 10,346 pounds (Table 6), and the mean cycle time required to chip that 
## load was 15.3 minutes. So, one PMH would be chipping somewhere around 4 complete forwarder 
## loads, which would yield a little over 41,000 pounds. Just over 20 tons. Looks good. Corresponds with ## results described at the bottom of p. 187, right hand column.

**Comment by RobKeefe** [comment]
Sorry about the formatting; a function of pasting comment characters in. Will fix that at some point, or feel free to...

**Comment by jsfried** [comment]
formatting is the least of my worries, but thank you.

I have re-read your interpretation several times. Perhaps I am dense, but I am having trouble seeing how the number of turns per hour and weight per turn are relevant, at least in terms of applying the equation in OpCost, as it seems to me like those drop out of the calculation. We can assume any weight of material to be chipped, per turn of the forwarder/skidder or yarder (WT)- you posited 5000 pounds, so applying the eqn we can get time in minutes per turn as 0.0015 * 5000.  We know how much weight per acre needs to be chipped and can divide that by WT to get number of turns, but to calculate chipper time, we are just going to multiply turn count by weight per turn to get total chipper time per acre. How will that result be any different than 0.0015 * Total Weight to be chipped, and if different, why?

As an aside, the weight of material to be chipped from each turn will be only a fraction of the weight carried by the forwarder/skidder/yarder as I assume that materials are mixed (merch logs along with non-merch logs in case of log length systems like tethered, and tops and limbs along with boles in whole tree systems, which of course would also require a processor on landing to separate those parts before chippping, at least for the trees containing logs of merchantable size and species).

I will leave to Carlin the coding decisions about where and how to translate volume to green weight (via the density metrics provided in BioSum), where to use minutes vs hours, etc. as she has a good sense of where the efficiencies are to be found. Just drafting the particulars of the tethered system implementation, I could see that it is VERY easy to make mistakes on units in this kind of accounting work, so thanks for the reminder,

**Comment by RobKeefe** [comment]
Hi Jeremy,

This is my only chance for communication until late this evening. After sleeping a relatively small amount, I edited that post slightly this morning. Not sure if you re-read while it was being edited or 
not, but the key item was this last line:

"[Rob left off here in wee hours of morning...]." 

...And also my separate email to you which I've documented here:
"From: Keefe, Robert (robk@uidaho.edu)
To: Fried, Jeremy - FS; Carlin Starrs
Subject:
Item 28
Date:
Friday, April 13, 2018 9:36:00 AM
Hi Jeremy and Carlin,
I worked on an explanation for Issue/question #28 (implementation of Bolding equation) a bit until
nodding off… Will try to get back to it today to complete that if I can find a free spot. Looking
at my schedule, that will most likely be at a similar time of day…
Rob"

So, should be clear that I was not quite finished. :) Yes, it's a very simple function in the paper paper, multiplying a single coefficient by one independent variable estimated from the stand conditions. You asked for my interpretation and explanation, so I have been taking the time to provide an example of working through it, with some alternative options for units, etc. so that it's as clear as possible. I think in terms of rates per PMH and per unit volume, so always look at processes in those units so I can understand them, and whether the numbers are reasonable.  

JS wrote: "As an aside, the weight of material to be chipped from each turn will be only a fraction of the weight carried by the forwarder/skidder/yarder as I assume that materials are mixed (merch logs along with non-merch logs in case of log length systems like tethered, and tops and limbs along with boles in whole tree systems, which of course would also require a processor on landing to separate those parts before chippping, at least for the trees containing logs of merchantable size and species)."   

Yes, absolutely. You are definitely correct that only non-sawlog material should be chipped in a given BioSum scenario / OpCost harvest system combination, unless sawlogs are being chipped in that scenario for some reason. So, as you and Carlin rework how and when the material routed for chipping is designated, this Bolding equation should only take the component of material to be chipped as input. 

 I will revisit this thread once more late this evening and hopefully we can put this one to bed. In general, I think it's a relatively simple function, as you can see, and really comes down to how and when you and Carlin are best retaining consistency of units in different places in the new code.

Hope that helps! 
Rob

**Comment by jsfried** [comment]
Carlin has structured the new code with tables for equations and tables for unit conversions-- it is really pretty slick and helps manage some of the unit confusion better than before. Based on your analysis of Bolding, we are calculating chipping time as 0.0015 * m$ChipFeedstockWeight with units in min/acre. Thanks for walking us through this one.

**Comment by RobKeefe** [comment]
Yes, I did look through the tables and the code the other day. I
understand, and was impressed. I think this approach works great for this
purpose, and Carlin has done an outstanding job! It's a more conventional
methodology and will work great for BioSum upkeep and growth. There was,
long ago, a fleeting idea behind the way it had been structured with
individual functions coded, FWIW. The idea was to have each function
developed considerably more and with some very different functionality.
They were to be documented in the usual way (individually, in an R package)
with the associated publication(s) and examples. And, importantly, each was
to be associated with a method call for objects (in the OO sense) that
would be a new equipment class (in R). These would provide the usual forest
operations / forest engineering outputs, and interact with individual
tree-based models, spatial data, etc. in some different ways based on their
attributes (e.g. equipment weight, etc.).  And, there was to be more
emphasis on other sorts of things that folks in forest operations/forest
engineering are interested in quantifying when doing analyses other than
those that occur within BioSum. Since those other things were not needed
for the BioSum simulations, the marginal importance of moving ahead in
those other directions fizzled out early on. Just mentioning this so you
know that there was at least a little thinking behind why the code
originally had separate functions... They were seeds that never took, or
placeholders for going a different direction. Our lab group will move
forward that other approach in our R package one of these days (the plan is
to start on it this fall), to go along with some very different ways of
estimating treatment costs that we are developing. Anyhow... glad this item
is resolved now and closed. Keep up the great work, Carlin- You are really
doing an amazing job and it's appreciated! Rob

**Comment by carlinstarrs** [comment]
Interesting! Yes, my focus was very much biosum oriented, but hopefully if folks take it up they can adapt it. I'm happy to help with any such effort but will add the caveat that I'll be starting a new position this fall and my time may be limited. But I may not be that helpful anyway since what you describe is a bit beyond what I've done before :)

**Comment by RobKeefe** [comment]
I think the way you have this set up now is perfect for BioSum and the best way to do it. The other approach has a home in our real time analytics research (https://www.researchgate.net/project/Real-time-location-and-data-sharing-for-forestry-and-natural-resources). We work with costs in a very different way in those projects, based on high resolution temporal data. We simulate all the equipment and employee movements (position, orientation, etc.) as they work through the stand, so that the operators / workers / foresters can see system dynamics on phones or watches within a few seconds as they work. So, definitely a different sort of data and resolution than needs to be in BioSum. 

I think your approach with the reinvigorated OpCost is really strong and flexible, as there's a consistent framework and both you and Jeremy have a good understanding of the architecture now, which is most important. It's very well organized and your work is extremely detail-oriented. So, one can easily add other functions, etc. in the future in a straight-forward way. There is really only one main addition I would recommend if Jeremy feels it worthy at some point. It is something Jeremy and I discussed on the phone last week and could be added as a different 'issue' at some point, probably not until after resolving current open issues. Or, we could all touch base briefly on the phone at some point. Given your coding skills, it would be quick for you to do, as there is lots of very good documentation and it would systematically drop into your current structure very nicely. It would be just adding the classical 'machine rate' calculations as the basis for populating values in the 'opcost_cost_ref.csv'. So, rather than having fixed values assumed for hourly rates, you would have these estimated as a function of equipment purchase price, fuel consumption, etc. That will generally allow BioSum to stay current over time, as new equipment prices can be updated. And, the utilization rate assumed for each piece of equipment can be adaptive for different users over time. That is a main source of variability in logging/treatment costs, both in reality and in modeling. See, e.g., Brinker et al. (2002) which is a great reference on machine rates: https://www.fs.usda.gov/treesearch/pubs/33467). We do some exercises developing machine rates as the basis for logging costs in my Forest Operations class, so I'm happy to provide some example Excel spreadsheets and/or R code at some point. I think that's the max level of detail needed to have OpCost a bit more resilient and adaptable for long term success within BioSum. You are doing really great work, Carlin-
