### ISSUE TITLE
Verify eqn to calculate dbh from twitchvol

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia_Biosum_Scripts#29]
OpCost contains code to calculate average diameter from twitchvol as
dbh <- sqrt((m$twitchVol + 8.4166)/.2679)

Because we are using this equation in calculating chainsaw felling costs, seek certainty and provenance, Can you provide a reference or derivation?

Can you verify that it works whether calculating twitchvol as average volume per tree of all trees in the stand (if for example applying chainsaw felling to all tree size classes) AND if twitchvol is calculated say just for large log trees (because manual felling is applied only to those trees)?

Thanks.

**Comment by RobKeefe** [comment]
Hi Carlin, I was hoping we might hear back on the reference for this one, but no luck. I have worked through a few iterations and can't reproduce the function based on common assumptions for tree geometry and/or units that might be used in operations research. However, after some sleuthing, I at least found that the form is the same as the default function that was used in earlier versions of FRCS, although the parameter estimates are different. The function in FRCS is - sigh - also without a reference as far as I can tell. It was the following: DBH = sqrt((Vol+3.675)/0.2679). Not sure why they differ. Since they're otherwise similar (in form), it may be that the constants changed in subsequent versions of FRCS and the original OpCost coder found a different version somewhere along the way.

I compared the results of the function with each pair of parameter estimates and the results are pasted below. I added a horizontal line to show the break between default small and large log volumes assumed in FRCS (80 CF). I'm not sure where this leaves us. Perhaps you could refer to the FRCS documentation as the source? Hope that helps. Unfortunately all I have time for until sometime later this week. Code for the figure is below. Rob

![image](https://user-images.githubusercontent.com/38309140/39231244-426ec836-481e-11e8-9f49-d7f04e3fce1e.png)


Here is the code I used to generate the comparison:

```
# RK, 4/24/18. OpCost default function for estimating DBH (in) from volume (CF)
# for both small and large trees.  
      
  OpCostDBH <- function(Vol) { 
    
    sqrt((Vol + 8.4166)/0.2679)
    
  }

# RK, 4/24/18. Corresponding FRCS west coefficients:

FRCSDBH <- function(Vol) { 
  
  sqrt((Vol + 3.675)/.216)
  
} 

# RK, 4/24/18. Assume volumes from 1 to 250 CF: 

Vol <- 1:250 

OpCostDBHest <- OpCostDBH(Vol) 
FRCSDBHest <- FRCSDBH(Vol)

# RK, 4/24/18. Generate a plot across a plausible range of volumes to compare, showing the 
# assume 80 CF split between small and large log volumes:

pdf("D://Rob/Faculty/Advising/Bell/OpCost help - 2018/Issue 29/Figures/OpCost and FRCS DBH-Vol.pdf")

plot(Vol ~ OpCostDBHest, 
     ylab="Vol (CF)",
     xlab="DBH (in)",
     xlim=c(-2,37),
     ylim=c(-5,255),
     type="l",
     col="royalblue")
par(new=T)
plot(Vol ~ FRCSDBHest, 
     ylab="Vol (CF)",
     xlab="DBH (in)",
     xlim=c(-2,37),
     ylim=c(-5,255),
     type="l",
     col="seagreen3")

abline(h=80,
       col="red",
       lwd=1.5,
       lty=2)

dev.off()


```

**Comment by jsfried** [comment]
Thanks for looking into this, Rob. Since we have a tree list in BioSum, we don't really need to derive average DBH for a diameter class so indirectly-- is there any reason you can think of why we would not (ultimately) pass, from BioSum to OpCost, the avg diameter of each tree size class (BC, CT, SLT, LLT)  directly? If so, should it be a TPAxvolume weighted average, just TPA weighted, or something else?

**Comment by jsfried** [comment]
Having not heard back from Rob on these last questions, and needing to close on this issue, since we do not have the resources at this time to pass DBH per size class to OpCost and have OpCost calculate machine time separately for each size class (which would likely be more accurate), I took a look at impact of the two equation forms (unreferenced OC and unreferenced FRCS). These are summarized for some common California species based on a sample of FIA tree data for which Volume Total Stem Gross Cubic Feet had been calculated by FIA, for a few species and DBHs. The upshot:
OC eqn appears to fit better than FRCS; neither is great at high DBH (estimated DBH is always biased low); some species are closer than others.
@carlinstarrs 
[verification_of_dbh_calcs_20180614.xlsx](https://github.com/USFS-PNW/Fia_Biosum_Scripts/files/2103526/verification_of_dbh_calcs_20180614.xlsx)
