### ISSUE TITLE
Speed of OpCost 10?

### ISSUE THREAD

**Issue by RobKeefe** [USFS-PNW/Fia_Biosum_Scripts#30]
Not sure if this is appropriate to post as it's more of a curiosity question than an 'issue' with the code, per se. But, just wondering if OpCost 10 has been run with BioSum and, if so, how the speed is? Faster than the earlier versions? Thanks! Rob

**Comment by carlinstarrs** [comment]
Hi! It'll depend how many harvest systems and equations we wind up using to compare for the optimization, but right now it takes about 2-3 seconds if you're just using 1 harvest system. With 12 harvest systems to choose from and 70 or so equations it may take 1-2 minutes.  There is some potential room for optimization since equations might get calculated multiple times if they're used in multiple harvest systems, but it's hard to say for sure.

**Comment by RobKeefe** [comment]
Nice! Thanks for your thoughts on it- Again, great work.

**Comment by carlinstarrs** [comment]
I just tested this with the largest package I could find in the CA variant and it ran with all the harvest systems enabled in about 8 seconds, apparently it's faster than I guessed!
